### ISSUE TITLE
New functions for associated NEON data with individual trees

### ISSUE THREAD

**Issue by bw4sz** [weecology/TreeSegmentation#1]
* Download data NEON (non-aop)
* Combine data files by site for the plant foliar and chemical data, and field data. (need data product IDs).
This creates a single file for all sites for a given data product. Create a giant dataframe with coordinate + trait data/species.
* Determine which flightpath is associated with each tree individual. Generate a list of data products (aop) that need to be run.

@Marconi_S has been working similar functions, can clone and add to functions.

**Comment by MarconiS** [comment]
this has been done (is on a different repo of mine for convenience. When we need to merge we can try to merge the two, since I've made the pipeline of mine modular so that it can be integrated easily in your pipeline :)
