### ISSUE TITLE
Distortion in the L1 rgb imagery, confirm whether we are consistently using L1 or L3 products.

### ISSUE THREAD

**Issue by bw4sz** [weecology/TreeSegmentation#3]
We need to email NEON to get a sense for whether we should be using the L1 or L3 orthophoto products.

Here it looks like i've been using the L1 product to crop the 2017

https://github.com/weecology/TreeSegmentation/blob/ede4d4fcc53cdba44ebdec20a4e3e960d6b99baf/analysis/Crop_RGB.R#L31

because the L3 overlap wasn't complete with all of our ground truth data. That's fine for validation, but for training, which should we use?

In the L1, i'm getting some distortion

![osbs_006](https://user-images.githubusercontent.com/1208492/41996991-806e0880-7a0b-11e8-953c-8d100a925998.png)

I need to confirm whether it looks similar in L3, or some data processing improves this. It could go the other way and make it worse during the tiling.

@MarconiS just uploaded the L3 product for  [2015.](https://github.com/weecology/DeepForest/issues/2)

TODO: to check with NEON if this expected/reaches their data quality threshold. Not clear to me if L1 or L3 should be better quality.

**Comment by MarconiS** [comment]
my understanding from what I saw is that the L3 is that they just bind together the pieces of L1 more central (in order to reduce distortion). The problem may be how much time the L3 cropped data take to be released, and the absence of a cloudiness quality check when merging the flight paths. Other thing not 100% clear to me is if the L3 data are processed so that pieces of different flightpaths are harmonized (e.g. avoid to have half tile darker half brighter just because accessory conditions)

**Comment by bw4sz** [comment]
Closing this, response from tristan. I'm far from convinced, but I do not see an action item.

Hi Ben,

 

Thanks for your note. You are correct that this is an artifact that results from the differing spatial resolutions of the datasets. We do the ortho-rectification of the camera images using a DSM, which contains tree features, and is also at 1 m spatial resolution. The camera images are created at 10 cm resolution. Trying to ortho-rectify the high resolution camera images onto the lower resolution DSM results in these artifacts.

 

Can you confirm whether the artifacts you see are near the center of an ortho-image, where center means lowest nadir angle? Generally the distortions are minimized near the center of images. The mosaics are created using the center-most pixels and typically the distortions are not as obvious in the mosaics. Is this affect pervasive through all the mosaic images at OSBS 2017? 

-Tristan
