### ISSUE TITLE
Field data retriever.

### ISSUE THREAD

**Issue by bw4sz** [weecology/TreeSegmentation#7]
Link to code for downloading new site field data (i'll need to do SJER):

Can you point to where i'd need to modify the code to optionally not drop no azimuth/direction trees. In case we want to start using tree counts within plots as an evaluation metric.

**Comment by MarconiS** [comment]
oki! the field data retriever is in https://github.com/MarconiS/TOS_retriever. Will follow soon a little description file. The function you are interested in is `get_vegetation_structure()` It doesn't need any argument, it will download merge and supposedly clean data for 39ish sites. Enjoy!

**Comment by bw4sz** [comment]
By default does it drop the trees with no azimuth data? Just thinking about the idea of total tree count?

**Comment by MarconiS** [comment]
just added a flag `geo_only` which if turn false will return the entire cleaned  vegetation structure dataset

**Comment by bw4sz** [comment]
I grabbed the code and documented it with a couple roxygen tags.  Looks good as a start. Not clear which plots are trustworthy total counts (see slack). Thanks!
